<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.16">
  <POU Name="MAIN" Id="{16be0fc6-ae40-4a05-90aa-9d2fd038dc01}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_DIAGNOSTIC();
PRG_SXR_VAC();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>